export const homeSliderBannerKey = "home-slider-banners";
export const singleBannerKey = "single-banner";
export const topProductsKey = "topProducts";
export const latestProductsKey = "latestProducts";
export const comboProductsKey = "comboProducts";
export const productCategoriesKey = "productCategories";
export const productCategoriesWithImageKey = "productCategoriesWithImage";
export const getUserNotificationKey = (userId:string) => `userNotifications-${userId}`;
export const getUserNotReadNotificationCountKey = (userId:string) => `userNotReadNotificationsCount-${userId}`;
export const getUserCartItemKey = (userId:string) => `userCartItem-${userId}`;
export const getUserCartCountKey = (userId:string) => `userCartCounts-${userId}`;
export const getUserCheckoutWalletsKey = (userId:string) => `userCheckoutWallets-${userId}`;
export const getUserOrdersKey = (userId:string) => `userOrders-${userId}`;
export const getUserOrderDetailsKey = (orderUd:string) => `userOrderDetails-${orderUd}`;
export const getProductRatingKey = (productId:string) => `product-rating-${productId}`;
export const getProductRatingAndReviewsKey = (productId:string) => `product-ratingAndReviews-${productId}`;
export const getUserReferDashboardKey = (userId:string) => `userReferDashboard-${userId}`;
export const getUserReferShortDashboardKey = (userId:string) => `userReferShortDashboard-${userId}`;
export const getUserProfileKey = (userId:string) => `userProfile-${userId}`;
export const getUserAddressesKey = (userId:string) => `userAddresses-${userId}`;
export const getUserWishlistKey = (userId:string) => `userWishlist-${userId}`;
export const getProductDetailsKey = (productId:string) => `product-details-${productId}`;
export const getAuthUserKey = (userId:string) => `auth-${userId}`;